# Generated by Django 4.2 on 2023-04-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_alter_todoitem_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="todo_app.todoitem",
            ),
        ),
    ]
